### ISSUE TITLE
Push to other registries than docker.io

### ISSUE THREAD

**Issue by janisz** [tonistiigi/binfmt#189] opened 2024-07-17 15:46 UTC
Due to throttling and limits imposed by Docker, it can be challenging to use this popular image, especially when employing the qemu docker action for installations. To alleviate this, could you consider pushing the image to additional registries such as [quay.io](https://quay.io/) or [ghcr.io](https://github.com/features/packages)? This would provide more flexibility and accessibility for users.

**Comment by jennydaman** [comment] 2024-08-29 04:39
Duplicate of #155

**Closed** 2024-08-29 11:16 UTC
